export type Tags = {
    value: string,
    label: string
}

export const Type: Tags[] = [
    { value: "artifact", label: "Artifact" },
    { value: "battle", label: "Battle" },
    { value: "conspiracy", label: "Conspiracy" },
    { value: "creature", label: "Creature" },
    { value: "dragon", label: "Dragon" },
    { value: "elemental", label: "Elemental" },
    { value: "enchantment", label: "Enchantment" },
    { value: "goblin", label: "Goblin" },
    { value: "hero", label: "Hero" },
    { value: "instant", label: "Instant" },
    { value: "jaguar", label: "Jaguar" },
    { value: "kindred", label: "Kindred" },
    { value: "knights", label: "Knights" },
    { value: "land", label: "Land" },
    { value: "legend", label: "Legend" },
    { value: "phenomenon", label: "Phenomenon" },
    { value: "plane", label: "Plane" },
    { value: "planeswalker", label: "Planeswalker" },
    { value: "scheme", label: "Scheme" },
    { value: "sorcery", label: "Sorcery" },
    { value: "stickers", label: "Stickers" },
    { value: "summon", label: "Summon" },
    { value: "tribal", label: "Tribal" },
    { value: "universewalker", label: "Universewalker" },
    { value: "vanguard", label: "Vanguard" },
    { value: "wolf", label: "Wolf"  },
]

export const Subtype: Tags[] = [
    { value: "abian", label: "Abian" },
    { value: "adventure", label: "Adventure" },
    { value: "advisor", label: "Advisor" },
    { value: "aetherborn", label: "Aetherborn" },
    { value: "ajani", label: "Ajani" },
    { value: "alara", label: "Alara" },
    { value: "alfava+metraxis", label: "Alfava Metraxis" },
    { value: "alicorn", label: "Alicorn" },
    { value: "alien", label: "Alien" },
    { value: "ally", label: "Ally" },
    { value: "aminatou", label: "Aminatou" },
    { value: "amonkhet", label: "Amonkhet" },
    { value: "and%2For", label: "and/or" },
    { value: "androzani+minor", label: "Androzani Minor" },
    { value: "angel", label: "Angel" },
    { value: "angrath", label: "Angrath" },
    { value: "antausia", label: "Antausia" },
    { value: "antelope", label: "Antelope" },
    { value: "apalapucia", label: "Apalapucia" },
    { value: "ape", label: "Ape" },
    { value: "arcane", label: "Arcane" },
    { value: "arcavios", label: "Arcavios" },
    { value: "archer", label: "Archer" },
    { value: "archon", label: "Archon" },
    { value: "arkhos", label: "Arkhos" },
    { value: "arlinn", label: "Arlinn" },
    { value: "armadillo", label: "Armadillo" },
    { value: "art", label: "Art" },
    { value: "artificer", label: "Artificer" },
    { value: "ashiok", label: "Ashiok" },
    { value: "assassin", label: "Assassin" },
    { value: "assembly-worker", label: "Assembly-Worker" },
    { value: "astartes", label: "Astartes" },
    { value: "atog", label: "Atog" },
    { value: "attraction", label: "Attraction" },
    { value: "aura", label: "Aura" },
    { value: "aurochs", label: "Aurochs" },
    { value: "autobot", label: "Autobot" },
    { value: "avatar", label: "Avatar" },
    { value: "azgol", label: "Azgol" },
    { value: "azra", label: "Azra" },
    { value: "background", label: "Background" },
    { value: "baddest", label: "Baddest," },
    { value: "badger", label: "Badger" },
    { value: "bahamut", label: "Bahamut" },
    { value: "barbarian", label: "Barbarian" },
    { value: "bard", label: "Bard" },
    { value: "basilisk", label: "Basilisk" },
    { value: "basri", label: "Basri" },
    { value: "bat", label: "Bat" },
    { value: "bear", label: "Bear" },
    { value: "beast", label: "Beast" },
    { value: "beaver", label: "Beaver" },
    { value: "beeble", label: "Beeble" },
    { value: "beeholder", label: "Beholder" },
    { value: "belenon", label: "Belenon" },
    { value: "berserker", label: "Berserker" },
    { value: "biggest", label: "Biggest," },
    { value: "bird", label: "Bird" },
    { value: "boar", label: "Boar" },
    { value: "b.o.b", label: "B.O.B." },
    { value: "bobblehead", label: "Bobblehead" },
    { value: "bolas", label: "Bolas" },
    { value: "bolas's+meditation+realm", label: "Bolas's Meditation Realm" },
    { value: "braniac", label: "Brainiac" },
    { value: "bringer", label: "Bringer" },
    { value: "brushwagg", label: "Brushwagg" },
    { value: "bureaucrat", label: "Bureaucrat" },
    { value: "byode", label: "Byode" },
    { value: "calix", label: "Calix" },
    { value: "camel", label: "Camel" },
    { value: "capenna", label: "Capenna" },
    { value: "capybara", label: "Capybara" },
    { value: "carrier", label: "Carrier" },
    { value: "cartouche", label: "Cartouche" },
    { value: "case", label: "Case" },
    { value: "cat", label: "Cat" },
    { value: "cave", label: "Cave" },
    { value: "centaur", label: "Centaur" },
    { value: "cephalid", label: "Cephalid" },
    { value: "chameleon", label: "Chameleon" },
    { value: "chandra", label: "Chandra" },
    { value: "chicken", label: "Chicken" },
    { value: "child", label: "Child" },
    { value: "chimera", label: "Chimera" },
    { value: "chorus", label: "Chorus" },
    { value: "citizen", label: "Citizen" },
    { value: "clamfolk", label: "Clamfolk" },
    { value: "class", label: "Class" },
    { value: "cleric", label: "Cleric" },
    { value: "cloud", label: "Cloud" },
    { value: "clown", label: "Clown" },
    { value: "clue", label: "Clue" },
    { value: "cockatrice", label: "Cockatrice" },
    { value: "comet", label: "Comet" },
    { value: "construct", label: "Construct" },
    { value: "contraption", label: "Contraption" },
    { value: "cow", label: "Cow" },
    { value: "coward", label: "Coward" },
    { value: "coyote", label: "Coyote" },
    { value: "crab", label: "Crab" },
    { value: "cridhe", label: "Cridhe" },
    { value: "crocodile", label: "Crocodile" },
    { value: "c'tan", label: "C'tan" },
    { value: "curse", label: "Curse" },
    { value: "custodes", label: "Custodes" },
    { value: "cyberman", label: "Cyberman" },
    { value: "cyborg", label: "Cyborg" },
    { value: "cyclops", label: "Cyclops" },
    { value: "dack", label: "Dack" },
    { value: "dakkon", label: "Dakkon" },
    { value: "dalek", label: "Dalek" },
    { value: "daretti", label: "Daretti" },
    { value: "darillium", label: "Darillium" },
    { value: "dauthi", label: "Dauthi" },
    { value: "davriel", label: "Davriel" },
    { value: "deb", label: "Deb" },
    { value: "deer", label: "Deer" },
    { value: "demigod", label: "Demigod" },
    { value: "demon", label: "Demon" },
    { value: "desert", label: "Desert" },
    { value: "designer", label: "Designer" },
    { value: "detective", label: "Detective" },
    { value: "devil", label: "Devil" },
    { value: "dihada", label: "Dihada" },
    { value: "dinosaur", label: "Dinosaur" },
    { value: "djinn", label: "Djinn" },
    { value: "doctor", label: "Doctor" },
    { value: "dog", label: "Dog" },
    { value: "dominaria", label: "Dominaria" },
    { value: "domri", label: "Domri" },
    { value: "donkey", label: "Donkey" },
    { value: "dovin", label: "Dovin" },
    { value: "dragon", label: "Dragon" },
    { value: "drake", label: "Drake" },
    { value: "dreadnought", label: "Dreadnought" },
    { value: "drone", label: "Drone" },
    { value: "druid", label: "Druid" },
    { value: "dryad", label: "Dryad" },
    { value: "duck", label: "Duck" },
    { value: "dungeon", label: "Dungeon" },
    { value: "dwarf", label: "Dwarf" },
    { value: "earth", label: "Earth" },
    { value: "echoir", label: "Echoir" },
    { value: "efreet", label: "Efreet" },
    { value: "egg", label: "Egg" },
    { value: "elder", label: "Elder" },
    { value: "eldraine", label: "Eldraine" },
    { value: "eldrazi", label: "Eldrazi" },
    { value: "elemental", label: "Elemental" },
    { value: "elemental%3F", label: "Elemental?" },
    { value: "elephant", label: "Elephant" },
    { value: "elf", label: "Elf" },
    { value: "elk", label: "Elk" },
    { value: "ellywick", label: "Ellywick" },
    { value: "elminster", label: "Elminster" },
    { value: "elspeth", label: "Elspeth" },
    { value: "elves", label: "Elves" },
    { value: "employee", label: "Employee" },
    { value: "equilor", label: "Equilor" },
    { value: "equipment", label: "Equipment" },
    { value: "ergamon", label: "Ergamon" },
    { value: "ersta", label: "Ersta" },
    { value: "estrid", label: "Estrid" },
    { value: "etiquette", label: "Etiquette" },
    { value: "eye", label: "Eye" },
    { value: "fabacin", label: "Fabacin" },
    { value: "faerie", label: "Faerie" },
    { value: "ferret", label: "Ferret" },
    { value: "fiora", label: "Fiora" },
    { value: "fire", label: "Fire" },
    { value: "fish", label: "Fish" },
    { value: "flagbearer", label: "Flagbearer" },
    { value: "food", label: "Food" },
    { value: "forest", label: "Forest" },
    { value: "fortification", label: "Fortification" },
    { value: "fox", label: "Fox" },
    { value: "fractal", label: "Fractal" },
    { value: "freyalise", label: "Freyalise" },
    { value: "frog", label: "Frog" },
    { value: "fungus", label: "Fungus" },
    { value: "gallifrey", label: "Gallifrey" },
    { value: "gamer", label: "Gamer" },
    { value: "gargantikar", label: "Gargantikar" },
    { value: "gargoyle", label: "Gargoyle" },
    { value: "garruk", label: "Garruk" },
    { value: "gate", label: "Gate" },
    { value: "giant", label: "Giant" },
    { value: "gideon", label: "Gideon" },
    { value: "gith", label: "Gith" },
    { value: "gnoll", label: "Gnoll" },
    { value: "gnome", label: "Gnome" },
    { value: "goat", label: "Goat" },
    { value: "gobakhan", label: "Gobakhan" },
    { value: "goblin", label: "Goblin" },
    { value: "god", label: "God" },
    { value: "golem", label: "Golem" },
    { value: "gorgon", label: "Gorgon" },
    { value: "grandchild", label: "Grandchild" },
    { value: "gremlin", label: "Gremlin" },
    { value: "griffin", label: "Griffin" },
    { value: "grist", label: "Grist" },
    { value: "guest", label: "Guest" },
    { value: "guff", label: "Guff" },
    { value: "gus", label: "Gus" },
    { value: "hag", label: "Hag" },
    { value: "halfling", label: "Halfling" },
    { value: "harpy", label: "Harpy" },
    { value: "hatificer", label: "Hatificer" },
    { value: "head", label: "Head" },
    { value: "hellion", label: "Hellion" },
    { value: "hero", label: "Hero" },
    { value: "hippo", label: "Hippo" },
    { value: "hippogriff", label: "Hippogriff" },
    { value: "homarid", label: "Homarid" },
    { value: "homonculus", label: "Homunculus" },
    { value: "horror", label: "Horror" },
    { value: "horse", label: "Horse" },
    { value: "horsehead+nebula", label: "Horsehead Nebula" },
    { value: "huatli", label: "Huatli" },
    { value: "human", label: "Human" },
    { value: "hydra", label: "Hydra" },
    { value: "hyena", label: "Hyena" },
    { value: "igpay", label: "Igpay" },
    { value: "ikoria", label: "Ikoria" },
    { value: "illusion", label: "Illusion" },
    { value: "imp", label: "Imp" },
    { value: "incarnation", label: "Incarnation" },
    { value: "innistrad", label: "Innistrad" },
    { value: "inquisitor", label: "Inquisitor" },
    { value: "insect", label: "Insect" },
    { value: "inzerva", label: "Inzerva" },
    { value: "iquatana", label: "Iquatana" },
    { value: "ir", label: "Ir" },
    { value: "island", label: "Island" },
    { value: "ixalan", label: "Ixalan" },
    { value: "jace", label: "Jace" },
    { value: "jackal", label: "Jackal" },
    { value: "jared", label: "Jared" },
    { value: "jaya", label: "Jaya" },
    { value: "jellyfish", label: "Jellyfish" },
    { value: "jeska", label: "Jeska" },
    { value: "juggernaut", label: "Juggernaut" },
    { value: "kaito", label: "Kaito" },
    { value: "kaladesh", label: "Kaladesh" },
    { value: "kaldheim", label: "Kaldheim" },
    { value: "kamigawa", label: "Kamigawa" },
    { value: "kandoka", label: "Kandoka" },
    { value: "kangaroo", label: "Kangaroo" },
    { value: "karn", label: "Karn" },
    { value: "karsus", label: "Karsus" },
    { value: "kasmina", label: "Kasmina" },
    { value: "kavu", label: "Kavu" },
    { value: "kaya", label: "Kaya" },
    { value: "kephalai", label: "Kephalai" },
    { value: "key", label: "Key" },
    { value: "killbot", label: "Killbot" },
    { value: "kinshala", label: "Kinshala" },
    { value: "kiora", label: "Kiora" },
    { value: "kirin", label: "Kirin" },
    { value: "kithkin", label: "Kithkin" },
    { value: "knight", label: "Knight" },
    { value: "kobold", label: "Kobold" },
    { value: "kolbahan", label: "Kolbahan" },
    { value: "kor", label: "Kor" },
    { value: "koth", label: "Koth" },
    { value: "kraken", label: "Kraken" },
    { value: "kylem", label: "Kylem" },
    { value: "kyneth", label: "Kyneth" },
    { value: "lady", label: "Lady" },
    { value: "lair", label: "Lair" },
    { value: "lamia", label: "Lamia" },
    { value: "lammasu", label: "Lammasu" },
    { value: "leech", label: "Leech" },
    { value: "lesson", label: "Lesson" },
    { value: "leviathan", label: "Leviathan" },
    { value: "lhurgoyf", label: "Lhurgoyf" },
    { value: "licid", label: "Licid" },
    { value: "liliana", label: "Liliana" },
    { value: "lizard", label: "Lizard" },
    { value: "lobster", label: "Lobster" },
    { value: "locus", label: "Locus" },
    { value: "lolth", label: "Lolth" },
    { value: "lorwyn", label: "Lorwyn" },
    { value: "lukka", label: "Lukka" },
    { value: "luvion", label: "Luvion" },
    { value: "mammoth", label: "Mammoth" },
    { value: "manticore", label: "Manticore" },
    { value: "mars", label: "Mars" },
    { value: "master", label: "Master" },
    { value: "masticore", label: "Masticore" },
    { value: "mercadia", label: "Mercadia" },
    { value: "mercenary", label: "Mercenary" },
    { value: "merfolk", label: "Merfolk" },
    { value: "metathran", label: "Metathran" },
    { value: "mime", label: "Mime" },
    { value: "mine", label: "Mine" },
    { value: "minion", label: "Minion" },
    { value: "minotaur", label: "Minotaur" },
    { value: "minsc", label: "Minsc" },
    { value: "mirrodin", label: "Mirrodin" },
    { value: "mite", label: "Mite" },
    { value: "moag", label: "Moag" },
    { value: "mole", label: "Mole" },
    { value: "monger", label: "Monger" },
    { value: "mongoose", label: "Mongoose" },
    { value: "mongseng", label: "Mongseng" },
    { value: "monk", label: "Monk" },
    { value: "monkey", label: "Monkey" },
    { value: "moon", label: "Moon" },
    { value: "moonfolk", label: "Moonfolk" },
    { value: "mordenkainen", label: "Mordenkainen" },
    { value: "mount", label: "Mount" },
    { value: "mountain", label: "Mountain" },
    { value: "mouse", label: "Mouse" },
    { value: "mummy", label: "Mummy" },
    { value: "muraganda", label: "Muraganda" },
    { value: "mutant", label: "Mutant" },
    { value: "myr", label: "Myr" },
    { value: "mystic", label: "Mystic" },
    { value: "naga", label: "Naga" },
    { value: "nahiri", label: "Nahiri" },
    { value: "narset", label: "Narset" },
    { value: "nastiest", label: "Nastiest," },
    { value: "nautilus", label: "Nautilus" },
    { value: "necron", label: "Necron" },
    { value: "necros", label: "Necros" },
    { value: "nephilim", label: "Nephilim" },
    { value: "new+earth", label: "New Earth" },
    { value: "new+phyrexia", label: "New Phyrexia" },
    { value: "nightmare", label: "Nightmare" },
    { value: "nightstalker", label: "Nightstalker" },
    { value: "niko", label: "Niko" },
    { value: "ninja", label: "Ninja" },
    { value: "nissa", label: "Nissa" },
    { value: "nixilis", label: "Nixilis" },
    { value: "noble", label: "Noble" },
    { value: "noggle", label: "Noggle" },
    { value: "nomad", label: "Nomad" },
    { value: "nymph", label: "Nymph" },
    { value: "octopus", label: "Octopus" },
    { value: "ogre", label: "Ogre" },
    { value: "oko", label: "Oko" },
    { value: "ooze", label: "Ooze" },
    { value: "orc", label: "Orc" },
    { value: "orgg", label: "Orgg" },
    { value: "otter", label: "Otter" },
    { value: "ouphe", label: "Ouphe" },
    { value: "outside+mutter's+spiral", label: "Outside Mutter's Spiral" },
    { value: "ox", label: "Ox" },
    { value: "oyster", label: "Oyster" },
    { value: "pangolin", label: "Pangolin" },
    { value: "paratrooper", label: "Paratrooper" },
    { value: "peasant", label: "Peasant" },
    { value: "pegasus", label: "Pegasus" },
    { value: "penguin", label: "Penguin" },
    { value: "performer", label: "Performer" },
    { value: "pest", label: "Pest" },
    { value: "phelddagrif", label: "Phelddagrif" },
    { value: "phoenix", label: "Phoenix" },
    { value: "phyrexia", label: "Phyrexia" },
    { value: "phyrexian", label: "Phyrexian" },
    { value: "pilot", label: "Pilot" },
    { value: "pirate", label: "Pirate" },
    { value: "plains", label: "Plains" },
    { value: "plant", label: "Plant" },
    { value: "pony", label: "Pony" },
    { value: "porcupine", label: "Porcupine" },
    { value: "possum", label: "Possum" },
    { value: "power-plant", label: "Power-Plant" },
    { value: "powerstone", label: "Powerstone" },
    { value: "praetor", label: "Praetor" },
    { value: "primarch", label: "Primarch" },
    { value: "processor", label: "Processor" },
    { value: "proper", label: "Proper" },
    { value: "pyrulea", label: "Pyrulea" },
    { value: "quintorius", label: "Quintorius" },
    { value: "rabbit", label: "Rabbit" },
    { value: "rabiah", label: "Rabiah" },
    { value: "raccoon", label: "Raccoon" },
    { value: "ral", label: "Ral" },
    { value: "ranger", label: "Ranger" },
    { value: "rat", label: "Rat" },
    { value: "rath", label: "Rath" },
    { value: "ravnica", label: "Ravnica" },
    { value: "rebel", label: "Rebel" },
    { value: "reflection", label: "Reflection" },
    { value: "regatha", label: "Regatha" },
    { value: "rhino", label: "Rhino" },
    { value: "rigger", label: "Rigger" },
    { value: "robot", label: "Robot" },
    { value: "rogue", label: "Rogue" },
    { value: "rowan", label: "Rowan" },
    { value: "rune", label: "Rune" },
    { value: "sable", label: "Sable" },
    { value: "saga", label: "Saga" },
    { value: "saheeli", label: "Saheeli" },
    { value: "salamander", label: "Salamander" },
    { value: "samurai", label: "Samurai" },
    { value: "samut", label: "Samut" },
    { value: "sarkhan", label: "Sarkhan" },
    { value: "satyr", label: "Satyr" },
    { value: "scarecrow", label: "Scarecrow" },
    { value: "scientist", label: "Scientist" },
    { value: "scorpion", label: "Scorpion" },
    { value: "scout", label: "Scout" },
    { value: "segovia", label: "Segovia" },
    { value: "serpent", label: "Serpent" },
    { value: "serra", label: "Serra" },
    { value: "serra's+realm", label: "Serra’s Realm" },
    { value: "shade", label: "Shade" },
    { value: "shadowmoor", label: "Shadowmoor" },
    { value: "shaman", label: "Shaman" },
    { value: "shandalar", label: "Shandalar" },
    { value: "shapeshifter", label: "Shapeshifter" },
    { value: "shark", label: "Shark" },
    { value: "sheep", label: "Sheep" },
    { value: "shenming", label: "Shenmeng" },
    { value: "ship", label: "Ship" },
    { value: "shrine", label: "Shrine" },
    { value: "siege", label: "Siege" },
    { value: "siren", label: "Siren" },
    { value: "sivitri", label: "Sivitri" },
    { value: "skaro", label: "Skaro" },
    { value: "skeleton", label: "Skeleton" },
    { value: "slith", label: "Slith" },
    { value: "sliver", label: "Sliver" },
    { value: "sloth", label: "Sloth" },
    { value: "slug", label: "Slug" },
    { value: "snail", label: "Snail" },
    { value: "snake", label: "Snake" },
    { value: "soldier", label: "Soldier" },
    { value: "soltari", label: "Soltari" },
    { value: "sorin", label: "Sorin" },
    { value: "spacecraft", label: "Spacecraft" },
    { value: "spawn", label: "Spawn" },
    { value: "specter", label: "Specter" },
    { value: "spellshaper", label: "Spellshaper" },
    { value: "sphere", label: "Sphere" },
    { value: "sphinx", label: "Sphinx" },
    { value: "spider", label: "Spider" },
    { value: "spike", label: "Spike" },
    { value: "spirit", label: "Spirit" },
    { value: "sponge", label: "Sponge" },
    { value: "spy", label: "Spy" },
    { value: "squid", label: "Squid" },
    { value: "squirrel", label: "Squirrel" },
    { value: "starfish", label: "Starfish" },
    { value: "surrakar", label: "Surrakar" },
    { value: "svega", label: "Svega" },
    { value: "swamp", label: "Swamp" },
    { value: "synth", label: "Synth" },
    { value: "szat", label: "Szat" },
    { value: "tamiyo", label: "Tamiyo" },
    { value: "tarkir", label: "Tarkir" },
    { value: "tasha", label: "Tasha" },
    { value: "tefiri", label: "Teferi" },
    { value: "teyo", label: "Teyo" },
    { value: "tezzeret", label: "Tezzeret" },
    { value: "thalakos", label: "Thalakos" },
    { value: "the", label: "The" },
    { value: "the+abyss", label: "The Abyss" },
    { value: "the+dalek+asylum", label: "The Dalek Asylum" },
    { value: "the+library", label: "The Library" },
    { value: "theros", label: "Theros" },
    { value: "thopter", label: "Thopter" },
    { value: "thrull", label: "Thrull" },
    { value: "tibalt", label: "Tibalt" },
    { value: "tiefling", label: "Tiefling" },
    { value: "time", label: "Time" },
    { value: "time+lord", label: "Time Lord" },
    { value: "tower", label: "Tower" },
    { value: "townsfolk", label: "Townsfolk" },
    { value: "trap", label: "Trap" },
    { value: "treasure", label: "Treasure" },
    { value: "treefolk", label: "Treefolk" },
    { value: "trenzalore", label: "Trenzalore" },
    { value: "trilobite", label: "Trilobite" },
    { value: "troll", label: "Troll" },
    { value: "turtle", label: "Turtle" },
    { value: "tyranid", label: "Tyranid" },
    { value: "tyvar", label: "Tyvar" },
    { value: "ugin", label: "Ugin" },
    { value: "ulgrotha", label: "Ulgrotha" },
    { value: "unicorn", label: "Unicorn" },
    { value: "unknown+planet", label: "Unknown Planet" },
    { value: "urza", label: "Urza" },
    { value: "urza's", label: "Urza's" },
    { value: "valla", label: "Valla" },
    { value: "vampire", label: "Vampire" },
    { value: "vampyre", label: "Vampyre" },
    { value: "varmint", label: "Varmint" },
    { value: "vedalken", label: "Vedalken" },
    { value: "vehicle", label: "Vehicle" },
    { value: "venser", label: "Venser" },
    { value: "viashino", label: "Viashino" },
    { value: "villain", label: "Villain" },
    { value: "vivien", label: "Vivien" },
    { value: "volver", label: "Volver" },
    { value: "vraska", label: "Vraska" },
]

export const Supertype: Tags[] = [
    { value: "basic", label: "Basic" },
    { value: "legendary", label: "Legendary" },
    { value: "ongoing", label: "Ongoing" },
    { value: "snow", label: "Snow" },
    { value: "world", label: "World" },
]

export const CoreSets: Tags[] = [
    {label: "Alpha", value: "lea"},
    {label: "Beta", value: "leb"},
    {label: "Unlimited", value: "2ed"},
    {label: "Revised", value: "3ed"},
    {label: "Alpha (Online)", value: "1e"},
    {label: "Beta (Online)", value: "2e"},
    {label: "Unlimited (Online)", value: "2u"},
    {label: "Revised (Online)", value: "3e"},
    {label: "4th Edition", value: "4ed"},
    {label: "5th Edition", value: "5ed"},
    {label: "6th Edition", value: "6ed"},
    {label: "7th Edition", value: "7ed"},
    {label: "8th Edition", value: "8ed"},
    {label: "9th Edition", value: "9ed"},
    {label: "10th Edition", value: "10e"},
    {label: "Magic 2010", value: "m10"},
    {label: "Magic 2011", value: "m11"},
    {label: "Magic 2012", value: "m12"},
    {label: "Magic 2013", value: "m13"},
    {label: "Magic 2014", value: "m14"},
    {label: "Magic 2015", value: "m15"},
    {label: "Magic Origins", value: "ori"},
    {label: "Magic 2019", value: "m19"},
    {label: "Magic 2020", value: "m20"},
    {label: "Magic 2021", value: "m21"},
    {label: "Adventures in the Forgotten Realms", value: "afr"},
    {label: "Foundations", value: "fdn"}
]

export const ExpansionSets: Tags[] = [
    {label: "Arabian Nights", value: "arn"},
    {label: "Antiquities", value: "atq"},
    {label: "Legends", value: "leg"},
    {label: "The Dark", value: "drk"},
    {label: "Fallen Empires", value: "fem"},
    {label: "Homelands", value: "hml"},
    {label: "Ice Age", value: "ice"},
    {label: "Ice Age (original)", value: "ice2"},
    {label: "Alliances", value: "all"},
    {label: "Coldsnap", value: "csp"},
    {label: "Mirage", value: "mir"},
    {label: "Visions", value: "vis"},
    {label: "Weatherlight", value: "wth"},
    {label: "Tempest", value: "tmp"},
    {label: "Stronghold", value: "sth"},
    {label: "Exodus", value: "exo"},
    {label: "Urza's Saga", value: "usg"},
    {label: "Urza's Legacy", value: "ulg"},
    {label: "Urza's Destiny", value: "uds"},
    {label: "Masquerade", value: "mmq"},
    {label: "Nemesis", value: "nem"},
    {label: "Prophecy", value: "pcy"},
    {label: "Invasion", value: "inv"},
    {label: "Planeshift", value: "pls"},
    {label: "Apocalypse", value: "apc"},
    {label: "Odyssey", value: "ody"},
    {label: "Torment", value: "tor"},
    {label: "Judgement", value: "jud"},
    {label: "Onslaught", value: "ons"},
    {label: "Legions", value: "lgn"},
    {label: "Scourge", value: "scg"},
    {label: "Mirrodin", value: "mrd"},
    {label: "Darksteel", value: "dst"},
    {label: "Fifth Dawn", value: "5dn"},
    {label: "Champions of Kamigawa", value: "chk"},
    {label: "Betrayers of Kamigawa", value: "bok"},
    {label: "Saviors of Kamigawa", value: "sok"},
    {label: "Ravnica", value: "rav"},
    {label: "Guildpact", value: "gpt"},
    {label: "Dissension", value: "dis"},
    {label: "Time Spiral", value: "tsp"},
    {label: "Planar Chaos", value: "plc"},
    {label: "Future Sight", value: "fut"},
    {label: "Llorwyn", value: "lrw"},
    {label: "Morningtide", value: "mor"},
    {label: "Shadowmoor", value: "shm"},
    {label: "Eventide", value: "eve"},
    {label: "Shards of Alara", value: "ala"},
    {label: "Conflux", value: "con"},
    {label: "Alara Reborn", value: "arb"},
    {label: "Zendikar", value: "zen"},
    {label: "Worldwake", value: "wwk"},
    {label: "Rise of the Eldrazi", value: "roe"},
    {label: "Scars of Mirrodin", value: "som"},
    {label: "Mirrodin Besieged", value: "mbs"},
    {label: "New Phyrexia", value: "nph"},
    {label: "Innistrad", value: "isd"},
    {label: "Dark Ascension", value: "dka"},
    {label: "Avaycin Reborn", value: "avr"},
    {label: "Return to Ravnica", value: "rtr"},
    {label: "Gatecrash", value: "gtc"},
    {label: "Dragon's Maze", value: "dgm"},
    {label: "Theros", value: "ths"},
    {label: "Born of the Gods", value: "bng"},
    {label: "Journey into Nyx", value: "jou"},
    {label: "Khans of Tarkir", value: "ktk"},
    {label: "Fate Reforged", value: "frf"},
    {label: "Dragons of Tarkir", value: "dtk"},
    {label: "Battle for Zendikar", value: "bfz"},
    {label: "Oath of the Gatewatch", value: "ogw"},
    {label: "Shadows Over Innistrad", value: "soi"},
    {label: "Eldritch Moon", value: "emn"},
    {label: "Kaladesh", value: "kld"},
    {label: "Aether Revolt", value: "aer"},
    {label: "Amonkhet", value: "akh"},
    {label: "Hour of Devastation", value: "hou"},
    {label: "Ixalan", value: "xln"},
    {label: "Rivals of Ixalan", value: "rix"},
    {label: "Dominaria", value: "dom"},
    {label: "Guilds of Ravnica", value: "grn"},
    {label: "Ravnica Allegiance", value: "rna"},
    {label: "War of the Spark", value: "war"},
    {label: "Throne of Eldraine", value: "eld"},
    {label: "Theros: Beyond Death", value: "thb"},
    {label: "Ikoria: Lair of Behemoths", value: "iko"},
    {label: "Zendikar Rising", value: "znr"},
    {label: "Kaldheim", value: "khm"},
    {label: "Strixhaven: School of Mages", value: "stx"},
    {label: "Innistrad: Midnight Hunt", value: "mid"},
    {label: "Innistrad: Crimson Vow", value: "vow"},
    {label: "Kamigawa: Neon Dynasty", value: "neo"},
    {label: "Streets of New Capenna", value: "snc"},
    {label: "Dominaria United", value: "dmu"},
    {label: "The Brothers' War", value: "bro"},
    {label: "Phyrexia: All Will Be One", value: "one"},
    {label: "March of the Machine", value: "mom"},
    {label: "March of the Machine: The Aftermath", value: "mat"},
    {label: "Wilds of Eldraine", value: "woe"},
    {label: "Lost Caverns of Ixalan", value: "lci"},
    {label: "Murders at Karlov Manner", value: "mkm"},
    {label: "Outlaws of Thunder Junction", value: "otj"},
    {label: "The Big Score", value: "big"},
    {label: "Bloomburrow", value: "blb"},
    {label: "Duskmourn: House of Horror", value: "dsk"},
    {label: "Aetherdrift", value: "dft"},
    {label: "Tarkir: Dragonstorm", value: "tdm"}
]

export const CommandZoneSets: Tags[] = [
    { label: "Vanguard", value: "van"},
    { label: "Planechase", value: "hop"},
    { label: "Archenemy", value: "arc"},
    { label: "Commander", value: "cmd"},
    { label: "Planechase 2012", value: "pc2"},
    { label: "Commander's Arsenal", value: "cm1"},
    { label: "Commander 2013", value: "c13"},
    { label: "Conspiracy", value: "cns"},
    { label: "Commander 2014", value: "c14"},
    { label: "Commander 2015", value: "c15"},
    { label: "Conspiracy 2: Take the Crown", value: "cn2"},
    { label: "Commander 2016", value: "c16"},
    { label: "Planechase Anthology", value: "pca"},
    { label: "Commander Anthology", value: "cma"},
    { label: "Archenemy: Nicol Bolas", value: "e01"},
    { label: "Explorers of Ixalan", value: "e02"},
    { label: "Commander 2017", value: "c17"},
    { label: "Commander Anthology 2", value: "cm2"},
    { label: "Battlebond", value: "bbd"},
    { label: "Commander 2018", value: "c18"},
    { label: "Commander 2019", value: "c19"},
    { label: "Ikoria: Commander 2020", value: "c20"},
    { label: "Zendikar Rising: Commander Decks", value: "znc"},
    { label: "Commander Collection: Green", value: "cc1"},
    { label: "Commander Legends", value: "cmr"},
    { label: "Commander Legends Decks", value: "cmc"},
    { label: "Kaldheim Commander", value: "khc"},
    { label: "Commander 2021", value: "c21"},
    { label: "Forgotten Realms Commander", value: "afc"},
    { label: "Midnight Hunt Commander", value: "mic"},
    { label: "Crimson Vow Commander", value: "voc"},
    { label: "Commander Collection: Black", value: "cc2"},
    { label: "Kamigawa Commander", value: "nec"},
    { label: "Streets of New Capenna Commander", value: "ncc"},
    { label: "Commander Legends: Battle for Baldur's Gate", value: "clb"},
    { label: "Dominaria United Commander", value: "dmc"},
    { label: "Warhammer 40k", value: "40k"},
    { label: "The Brothers' War Commander", value: "brc"},
    { label: "Phyrexia: All Will Be One Commander", value: "onc"},
    { label: "March of the Machine Commander", value: "moc"},
    { label: "Starter Commander Decks", value: "scd"},
    { label: "Commander Masters", value: "cmm"},
    { label: "Lord of the Rings Commander", value: "ltc"},
    { label: "Wilds of Eldraine Commander", value: "woc"},
    { label: "Lost Caverns of Ixilan Commander", value: "lcc"},
    { label: "Murders at Karlov Manner Commander", value: "mkc"},
    { label: "Outlaws of Thunder Junction Commander", value: "otc"},
    { label: "Bloomburrow Commander", value: "blc"},
    { label: "Modern Horizons 3 Commander", value: "m3c"},
    { label: "Duskmourn Commander", value: "dsc"},
    { label: "Foundations Commander", value: "fdc"},
    { label: "Aetherdrift Commander", value: "drc"}
]

export const ReprintSets: Tags[] = [
    { label: "Chronicles", value: "chr"},
    { label: "Anthologies", value: "ath"},
    { label: "Battle Royale", value: "brb"},
    { label: "Beatdown", value: "btd"},
    { label: "Deckmasters", value: "dkm"},
    { label: "Modern Masters", value: "mma"},
    { label: "Modern Masters 2015", value: "mm2"},
    { label: "Eternal Masters", value: "ema"},
    { label: "Modern Masters 2017", value: "mm3"},
    { label: "Renaissance", value: "ren"},
    { label: "Rinascimento", value: "rin"},
    { label: "Iconic Masters", value: "ima"},
    { label: "Masters 25", value: "a25"},
    { label: "Ultimate Masters", value: "uma"},
    { label: "Modern Horizons", value: "mh1"},
    { label: "Double Masters", value: "2xm"},
    { label: "Jumpstart", value: "jmp"},
    { label: "Mystery Booster", value: "mb1"},
    { label: "Modern Horizons 2", value: "mh2"},
    { label: "Strixhaven: Mystical Archives", value: "sta"},
    { label: "Jumpstart: Historic Horizons", value: "j21"},
    { label: "Double Masters 2022", value: "2x2"},
    { label: "The Brothers War Retro Artifacts", value: "brr"},
    { label: "Jumpstart 2022", value: "j22"},
    { label: "Multiverse Legends", value: "mul"},
    { label: "Wilds of Eldraine Enchanting Table", value: "wot"},
    { label: "Battle Royale (alternate)", value: "br"},
    { label: "Special Guests", value: "spg"},
    { label: "Breaking News", value: "otp"},
    { label: "Mystery Booster 2", value: "mb2"},
    { label: "Jumpstart 2025", value: "j25"},
    { label: "Pioneer Masters", value: "pio"}
]

export const BeginnerSets: Tags[] = [
    { label: "Portal", value: "por"},
    { label: "Portal 2", value: "p02"},
    { label: "Portal Three Kingdoms", value: "ptk"},
    { label: "Starter 1999", value: "s99"},
    { label: "Starter 2000", value: "s00"},
    { label: "Welcome Deck 2016", value: "w16"},
    { label: "Welcome Deck 2017", value: "w17"}
]

export const DuelDecks: Tags[] = [
    { label: "Elves v. Goblins", value: "evg"},
    { label: "Jace v. Chandra", value: "dd2"},
    { label: "Divine v. Demonic", value: "ddc"},
    { label: "Garruk v. Liliana", value: "ddd"},
    { label: "Phyrexia v. Coalition", value: "dde"},
    { label: "Elspeth v. Tezzeret", value: "ddf"},
    { label: "Knights v. Dragons", value: "ddg"},
    { label: "Ajani v. Nicol Bolas", value: "ddh"},
    { label: "Venser v. Koth", value: "ddi"},
    { label: "Izzet v. Golgari", value: "ddj"},
    { label: "Sorin v. Tibalt", value: "ddk"},
    { label: "Heroes v. Monsters", value: "ddl"},
    { label: "Jace v. Vraska", value: "ddm"},
    { label: "Speed v. Cunning", value: "ddn"},
    { label: "Koira v. Elspeth", value: "ddo"},
    { label: "Zendikar v. Eldrazi", value: "ddp"},
    { label: "Blessed v. Cursed", value: "ddq"},
    { label: "Nissa v. Ob Nixilis", value: "ddr"},
    { label: "New Phyrexia v. Mirrodin Pure", value: "td2"},
    { label: "Mind v. Might", value: "dds"},
    { label: "Merfolk v. Goblins", value: "ddt"},
    { label: "Elves v. Inventors", value: "ddu"}
]

export const FromTheVaultSets: Tags[] = [
    { label: "FTV: Dragons", value: "drb"},
    { label: "FTV: Exiled", value: "v09"},
    { label: "FTV: Vaults", value: "v0x"},
    { label: "FTV: Relics", value: "v10"},
    { label: "FTV: Legends", value: "v11"},
    { label: "FTV: Realms", value: "v12"},
    { label: "FTV: Twenty", value: "v13"},
    { label: "FTV: Annihilation", value: "v14"},
    { label: "FTV: Angels", value: "v15"},
    { label: "FTV: Lore", value: "v16"},
    { label: "FTV: Transform", value: "v17"}
]

export const PremiumDecks: Tags[] = [
    { label: "PDS: Slivers", value: "h09"},
    { label: "PDS: Fire & Lightning", value: "pd2"},
    { label: "PDS: Graveborn", value: "pd3"},
    { label: "Modern Event Deck", value: "md1"}
]

export const SignatureSpellbooks: Tags[] = [
    { label: "Jace", value: "ss1"},
    { label: "Gideon", value: "ss2"},
    { label: "Chandra", value: "ss3"}
]

export const GlobalSeries = [{ label: "Jiang Yanggu & Mu Yanling", value: "gs: Tags[]1"}]

export const GuildKits: Tags[] = [
    { label: "Guild Kit: Azorius", value: "azorius"},
    { label: "Guild Kit: Boros", value: "boros"},
    { label: "Guild Kit: Dimir", value: "dimir"},
    { label: "Guild Kit: Golgari", value: "golgari"},
    { label: "Guild Kit: Gruul", value: "gruul"},
    { label: "Guild Kit: Izzet", value: "izzet"},
    { label: "Guild Kit: Orzhov", value: "orzhov"},
    { label: "Guild Kit: Rakdos", value: "rakdos"},
    { label: "Guild Kit: Selesnya", value: "selesnya"},
    { label: "Guild Kit: Simic", value: "simic"}
]

export const SupplimentalSets: Tags[] = [
    { label: "Game Night", value: "gnt"},
    { label: "GRN Guild Kits", value: "gk1"},
    { label: "RNA Guild Kits", value: "gk2"},
    { label: "Game Night 2019", value: "gn2"},
    { label: "Time Spiral Remastered", value: "tsr"},
    { label: "Dominaria Remastered", value: "dmr"},
    { label: "Game Night: Free For All", value: "gn3"},
    { label: "Lord of the Rings", value: "ltr"},
    { label: "UB: Doctor Who", value: "who"},
    { label: "Ravnica Remastered", value: "rvr"},
    { label: "Secret Lair", value: "sld"},
    { label: "UB: Fallout", value: "pip"},
    { label: "Ravnica: Clue Edition", value: "clu"},
    { label: "UB: Assassin's Creed", value: "acr"},
    { label: "Modern Horizons 3", value: "mh3"},
    { label: "Innistrad Remastered", value: "inr"}
]

export const PromotionalSets: Tags[] = [
    { label: "Duels of the Planeswalker", value: "dpa"},
    { label: "Zendikar Expeditions", value: "exp"},
    { label: "Kaladesh Inventions", value: "mp1"},
    { label: "Amonkhet Invocations", value: "mp2"},
    { label: "HasCon 2017", value: "h17"},
    { label: "Heroes of the Realm", value: "htr"},
    { label: "Mythic Edition", value: "med"},
    { label: "Ponies: The Gathering", value: "ptg"},
    { label: "Judge Academy 2020", value: "j20"},
    { label: "Zendikar Rising Expeditions", value: "zne"},
    { label: "The Brothers War Transformers", value: "bot"},
    { label: "Jurrassic World", value: "rex"}
]

export const OnlineSets: Tags[] = [
    { label: "Masters Edition I", value: "me1"},
    { label: "Masters Edition II", value: "me2"},
    { label: "Masters Edition III", value: "me3"},
    { label: "Masters Edition IV", value: "me4"},
    { label: "Vintage Masters", value: "vma"},
    { label: "Tempest Remastered", value: "tpr"},
    { label: "Legendary Cube", value: "pz1"},
    { label: "Magic Online", value: "xmodo"},
    { label: "Magic Duels", value: "xduels"},
    { label: "Magic Online Deck Series", value: "xmods"},
    { label: "Treasure Chests", value: "pz2"},
    { label: "Historic Anthology 1", value: "ha1"},
    { label: "Amonkhet Remastered", value: "akr"},
    { label: "Kaladesh Remastered", value: "klr"},
    { label: "Alchemy 2022", value: "y22"},
    { label: "Alchemy Horizons: Baldur's Gate", value: "hbg"},
    { label: "Alchemy: Dominaria", value: "ydmu"},
    { label: "Shadows Over Innistrad", value: "sir"},
    { label: "Shadows of the Past", value: "sis"},
    { label: "Explorer Anthology 1", value: "ea1"},
    { label: "Alchemy 2024", value: "y24"},
    { label: "Alchemy 2025", value: "y25"}
]

export const UnSeriousSets: Tags[] = [
    { label: "Unglued", value: "ugl"},
    { label: "Unhinged", value: "unh"},
    { label: "Unstable", value: "ust"},
    { label: "Unsanctioned", value: "und"},
    { label: "Unfinity", value: "unf"},
    { label: "Unfinity Acorns", value: "una"}
]

export const Sets: {label: string, value: Tags[]}[] = [
    { label: "Core Sets", value: CoreSets },
    { label: "Expansion Sets", value: ExpansionSets },
    { label: "Command Zone Sets", value: CommandZoneSets },
    { label: "Reprint Sets", value: ReprintSets },
    { label: "Beginner Sets", value: BeginnerSets },
    { label: "Duel Decks", value: DuelDecks },
    { label: "From The Vault", value: FromTheVaultSets },
    { label: "Premium Decks", value: PremiumDecks },
    { label: "Signature Spellbooks", value: SignatureSpellbooks },
    { label: "Global Series", value: GlobalSeries },
    { label: "Guild Kits", value: GuildKits },
    { label: "Supplimental Sets", value: SupplimentalSets },
    { label: "Promotional Sets", value: PromotionalSets },
    { label: "Online Exclusive Sets", value: OnlineSets },
    { label: "Un-Serious Sets", value: UnSeriousSets },
]

export const Types: {label: string, value: Tags[]}[] = [
    { label: "Supertypes", value: Supertype },
    { label: "Types", value: Type },
    { label: "Subtypes", value: Subtype }
]

export const Symbols: {label: string, value: string, category: string}[] = [
    { label: 'Tap This Permanent', value: '{T}', category: 'other'},
    { label: 'Untap This Permanent', value: '{Q}', category: 'other'},
    { label: 'One White Mana', value: '{W}', category: 'mana'},
    { label: 'One Blue Mana', value: '{U}', category: 'mana'},
    { label: 'One Black Mana', value: '{B}', category: 'mana'},
    { label: 'One Red Mana', value: '{R}', category: 'mana'},
    { label: 'One Green Mana', value: '{G}', category: 'mana'},
    { label: 'One Colorless Mana', value: '{C}', category: 'mana'},
    { label: 'One Energy Counter', value: '{E}', category: 'other'},
    { label: 'Modal Budget Pawprint', value: '{P}', category: 'other'},
    { label: 'Planeswalker', value: '{PW}', category: 'other'},
    { label: 'Chaos', value: '{CHAOS}', category: 'other'},
    { label: 'A Ticket Counter', value: '{TK}', category: 'other'},
    { label: 'X Generic Mana', value: '{X}', category: 'mana'},
    { label: 'Zero Mana', value: '{0}', category: 'mana'},
    { label: 'One Generic Mana', value: '{1}', category: 'mana'},
    { label: 'Two Generic Mana', value: '{2}', category: 'mana'},
    { label: 'Three Generic Mana', value: '{3}', category: 'mana'},
    { label: 'Four Generic Mana', value: '{4}', category: 'mana'},
    { label: 'Five Generic Mana', value: '{5}', category: 'mana'},
    { label: 'Six Generic Mana', value: '{6}', category: 'mana'},
    { label: 'Seven Generic Mana', value: '{7}', category: 'mana'},
    { label: 'Eight Generic Mana', value: '{8}', category: 'mana'},
    { label: 'Nine Generic Mana', value: '{9}', category: 'mana'},
    { label: 'Ten Generic Mana', value: '{10}', category: 'mana'},
    { label: 'Eleven Generic Mana', value: '{11}', category: 'mana'},
    { label: 'Twelve Generic Mana', value: '{12}', category: 'mana'},
    { label: 'Thirteen Generic Mana', value: '{13}', category: 'mana'},
    { label: 'Fourteen Generic Mana', value: '{14}', category: 'mana'},
    { label: 'Fifteen Generic Mana', value: '{15}', category: 'mana'},
    { label: 'Sixteen Generic Mana', value: '{16}', category: 'mana'},
    { label: 'Seventeen Generic Mana', value: '{17}', category: 'other'},
    { label: 'Eighteen Generic Mana', value: '{18}', category: 'other'},
    { label: 'Nineteen Generic Mana', value: '{19}', category: 'other'},
    { label: 'Twenty Generic Mana', value: '{20}', category: 'other'},
    { label: 'One White Mana or One Blue Mana', value: '{W/U}', category: 'mana'},
    { label: 'One White Mana or One Black Mana', value: '{W/B}', category: 'mana'},
    { label: 'One Blue Mana or One Black Mana', value: '{U/B}', category: 'mana'},
    { label: 'One Blue Mana or One Red Mana', value: '{U/R}', category: 'mana'},
    { label: 'One Black Mana or One Red Mana', value: '{B/R}', category: 'mana'},
    { label: 'One Black Mana or One Green Mana', value: '{B/G}', category: 'mana'},
    { label: 'One Red Mana or One Green Mana', value: '{R/G}', category: 'mana'},
    { label: 'One Red Mana or One White Mana', value: '{R/W}', category: 'mana'},
    { label: 'One Green Mana or One White Mana', value: '{G/W}', category: 'mana'},
    { label: 'One Green Mana or One Blue Mana', value: '{G/U}', category: 'mana'},
    { label: 'One White Mana, One Blue Mana, or 2 Life', value: '{W/U/P}', category: 'mana'},
    { label: 'One White Mana, One Black Mana, or 2 Life', value: '{W/B/P}', category: 'mana'},
    { label: 'One Blue Mana, One Black Mana, or 2 Life', value: '{U/B/P}', category: 'mana'},
    { label: 'One Blue Mana, One Red Mana, or 2 Life', value: '{U/R/P}', category: 'mana'},
    { label: 'One Black Mana, One Red Mana, or 2 Life', value: '{B/R/P}', category: 'mana'},
    { label: 'One Black Mana, One Green Mana, or 2 Life', value: '{B/G/P}', category: 'mana'},
    { label: 'One Red Mana, One White Mana, or 2 Life', value: '{R/W/P}', category: 'mana'},
    { label: 'One Red Mana, One Green Mana, or 2 Life', value: '{R/G/P}', category: 'mana'},
    { label: 'One Green Mana, One White Mana, or 2 Life', value: '{G/W/P}', category: 'mana'},
    { label: 'One Green Mana, One Blue Mana, or 2 Life', value: '{G/U/P}', category: 'mana'},
    { label: 'One Colored Mana or 2 Life', value: '{H}', category: 'other'},
    { label: 'One Colorless Mana or One White Mana', value: '{C/W}', category: 'mana'},
    { label: 'One Colorless Mana or One Blue Mana', value: '{C/U}', category: 'mana'},
    { label: 'One Colorless Mana or One Black Mana', value: '{C/B}', category: 'mana'},
    { label: 'One Colorless Mana or One Red Mana', value: '{C/R}', category: 'mana'},
    { label: 'One Colorless Mana or One Green Mana', value: '{C/G}', category: 'mana'},
    { label: '2 Generic Mana or One White Mana', value: '{2/W}', category: 'mana'},
    { label: '2 Generic Mana or One Blue Mana', value: '{2/U}', category: 'mana'},
    { label: '2 Generic Mana or One Black Mana', value: '{2/B}', category: 'mana'},
    { label: '2 Generic Mana or One Red Mana', value: '{2/R}', category: 'mana'},
    { label: '2 Generic Mana or One Green Mana', value: '{2/G}', category: 'mana'},
    { label: 'One White Mana or 2 Life', value: '{W/P}', category: 'mana'},
    { label: 'One Blue Mana or 2 Life', value: '{U/P}', category: 'mana'},
    { label: 'One Black Mana or 2 Life', value: '{B/P}', category: 'mana'},
    { label: 'One Red Mana or 2 Life', value: '{R/P}', category: 'mana'},
    { label: 'One Green Mana or 2 Life', value: '{G/P}', category: 'mana'},
    { label: 'One Snow Mana', value: '{S}', category: 'mana'},
]